# Default values for ppdd.
namespace: ppdd

replicaCount:
  ping: 1
  pong: 1
  ding: 1
  dong: 1

image:
  repository: ghcr.io/michaelerickson/
  image: ping-pong-ding-dong
  tag: 5148c3d2c3
  pullPolicy: IfNotPresent
  tagPing: 5148c3d2c3
  tagPong: 5148c3d2c3
  tagDing: 5148c3d2c3
  tagDong: 5148c3d2c3

imagePullSecrets:
    - name: ghcr.io

networking:
  pingPort: "8080"
  pongPort: "8080"
  dingPort: "8080"
  dongPort: "8080"

nodePorts:
    ping: "30001"
    pong: "30002"
    ding: "30003"
    dong: "30004"

#
#service:
#  type: ClusterIP
#  port: 80
#
#ingress:
#  enabled: false
#  className: ""
#  annotations: {}
#    # kubernetes.io/ingress.class: nginx
#    # kubernetes.io/tls-acme: "true"
#  hosts:
#    - host: chart-example.local
#      paths:
#        - path: /
#          pathType: ImplementationSpecific
#  tls: []
#  #  - secretName: chart-example-tls
#  #    hosts:
#  #      - chart-example.local
#
#resources: {}
#  # We usually recommend not to specify default resources and to leave this as a conscious
#  # choice for the user. This also increases chances charts run on environments with little
#  # resources, such as Minikube. If you do want to specify resources, uncomment the following
#  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
#  # limits:
#  #   cpu: 100m
#  #   memory: 128Mi
#  # requests:
#  #   cpu: 100m
#  #   memory: 128Mi
#
#autoscaling:
#  enabled: false
#  minReplicas: 1
#  maxReplicas: 100
#  targetCPUUtilizationPercentage: 80
#  # targetMemoryUtilizationPercentage: 80
#
#nodeSelector: {}
#
#tolerations: []
#
#affinity: {}
