# The Ping service
---
apiVersion: v1
kind: Service
metadata:
  name: ping
  labels:
      app: ping
spec:
  type: NodePort
  ports:
    - port: {{ .Values.networking.pingPort }}
      nodePort: {{ .Values.nodePorts.ping }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: ping
